dataset:
  train_fraction: 0.7
  val_fraction: 0.15
  batch_size: 1
  patch_size: [192, 192, 192]
  seed: 42

model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false
  reinit_weights: false

training:
  epochs: 10
  seed: 42
  use_deterministic_algorithms: true
  optimizer:
    lr: 0.0001
    weight_decay: 0.00003
    momentum: 0.99
    poly_power: 1.0
    nesterov: true

continual:
  strategy: cpe_clip
  output_dir: /home/vault/iwi5/iwi5326h/projects/VoxTell/experiments/continual/cpe_clip
  from_scratch: false
  cpe_clip:
    prompt_tokens: 2  
    prompt_layers: 3
    regularization_method: balance
    alpha_base: 1.0
    alpha_floor: 0.25
    prompt_init_std: 0.02
  tasks:
    - name: skm_tea_lateral_meniscus
      dataset:
        name: skm_tea_lateral_meniscus
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_medial_meniscus
      dataset:
        name: skm_tea_medial_meniscus
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_patellar
      dataset:
        name: skm_tea_patellar
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_femoral
      dataset:
        name: skm_tea_femoral
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/
    
    - name: skm_tea_medial_tibial
      dataset:
        name: skm_tea_medial_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_lateral_tibial
      dataset:
        name: skm_tea_lateral_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

  retention_tasks:
    - name: aeropath
      dataset:
        name: aeropath
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/AeroPath/
