dataset:
  train_fraction: 0.7
  val_fraction: 0.15
  batch_size: 1
  patch_size: [192, 192, 192]
  seed: 42
  train_max_cases: 2
  val_max_cases: 2
  test_max_cases: 2

model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false
  reinit_weights: false

training:
  epochs: 2
  seed: 42
  use_deterministic_algorithms: true
  optimizer:
    lr: 0.0001
    weight_decay: 0.00003
    momentum: 0.99
    poly_power: 1.0
    nesterov: true

continual:
  output_dir: ./experiments/continual/full_fine_tuning
  from_scratch: false
  tasks:
    - name: skm_tea_tibial
      dataset:
        name: skm_tea_tibial
        root: ./data/skm_tea/

    - name: skm_tea_meniscus
      dataset:
        name: skm_tea_meniscus
        root: ./data/skm_tea/

    - name: skm_tea_other
      dataset:
        name: skm_tea_other
        root: ./data/skm_tea/

  retention_tasks:
    - name: aeropath
      dataset:
        name: skm_tea_tibial
        root: ./data/AeroPath/