dataset:
  train_fraction: 0.7
  val_fraction: 0.15
  batch_size: 1
  patch_size: [192, 192, 192]
  seed: 42
  train_max_cases: 20

model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false
  reinit_weights: false

training:
  epochs: 10
  seed: 42
  use_deterministic_algorithms: true
  optimizer:
    lr: 0.0001
    weight_decay: 0.00003
    momentum: 0.99
    poly_power: 1.0
    nesterov: true

continual:
  strategy: shared_lora
  output_dir: /home/vault/iwi5/iwi5326h/projects/VoxTell/experiments/continual/lora/shared
  from_scratch: false
  lora:
    rank: 128
    alpha: 32
    dropout: 0.1
    # Restrict LoRA to TransformerDecoderLayer attention modules only.
    target_modules:
      - multihead_attn
    attn_parts: [q, v]
    bias: none
  tasks:
    - name: skm_tea_lateral_tibial
      dataset:
        name: skm_tea_lateral_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_medial_tibial
      dataset:
        name: skm_tea_medial_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_femoral
      dataset:
        name: skm_tea_femoral
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_patellar
      dataset:
        name: skm_tea_patellar
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_medial_meniscus
      dataset:
        name: skm_tea_medial_meniscus
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

  retention_tasks:
    - name: aeropath
      dataset:
        name: aeropath
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/AeroPath/
