dataset:
  name: veela
  root: ./data/VEELA Train Set/
  train_fraction: 0.7
  val_fraction: 0.15
  batch_size: 1
  patch_size: [192, 192, 192]
  seed: 42
  
model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false
  reinit_weights: false

training:
  epochs: 2
  seed: 42
  use_deterministic_algorithms: false
  optimizer:
    lr: 0.0001
    weight_decay: 0.00003
    momentum: 0.99
    poly_power: 1.0
    nesterov: true
  output_dir: ./experiments/fine_tuning/veela/dry_run
