dataset:
  name: fedbca_center2
  test_root: "./data/FedBCa/Center2/"
  seed: 42
  batch_size: 1

model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false

evaluation:
  output_dir: ./experiments/evaluations/fedbca_center2