dataset:
  train_fraction: 0.7
  val_fraction: 0.15
  batch_size: 1
  patch_size: [192, 192, 192]
  seed: 42

model:
  dir: ./models/voxtell_v1.1
  device: cpu
  deep_supervision: false

tsne:
  perplexity: 30.0
  seed: 42
  output: /home/vault/iwi5/iwi5326h/projects/VoxTell/experiments/tsne/tsne_continual_stage0.png
  n_samples: 1
  split: test
  embedding: mask
  stage: 0
  per_prompt: false
  datasets:
    - name: skm_tea_medial_meniscus
      dataset:
        name: skm_tea_medial_meniscus
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_patellar
      dataset:
        name: skm_tea_patellar
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_femoral
      dataset:
        name: skm_tea_femoral
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/
    
    - name: skm_tea_medial_tibial
      dataset:
        name: skm_tea_medial_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/

    - name: skm_tea_lateral_tibial
      dataset:
        name: skm_tea_lateral_tibial
        root: /home/vault/iwi5/iwi5326h/projects/VoxTell/data/skm_tea/
