dataset:
  name: veela
  test_root: "./data/VEELA Train Set/"
  seed: 42
  batch_size: 1

model:
  dir: ./models/voxtell_v1.1
  device: cuda
  deep_supervision: false

evaluation:
  output_dir: ./experiments/evaluations/veela